### ISSUE TITLE
Multiple adapters in a filesystem

### ISSUE THREAD

**Issue by Lumbendil** [KnpLabs/Gaufrette#133]
This is just a suggestion. It'd be nice to have multiple adapters bound to the same filesystem, to allow moving/copying between different adapters (for instance, moving uploaded files to an S3 bucket).

If you think it's worth a try, when I have some time I'll fork the project to see how it could be implemented.

**Comment by wysow** [comment]
@Lumbendil I think we can close this now right?

**Comment by Lumbendil** [comment]
@wysow I haven't been following this project as of late, but it seems quite dead, so yeah, I'll close it :)

**Comment by wysow** [comment]
@Lumbendil Thx and BTW a new version is under heavy development here https://github.com/Gaufrette ;)
