### ISSUE TITLE
url_stat requires write permissions

### ISSUE THREAD

**Issue by cuspide1988** [KnpLabs/Gaufrette#162]
Currently the url_stat method opens the file with "r+", thus failing if the file exists, but can't be written. If using url_stat in file_exists, this yields different results than doing a file_exists of an existing file on which you don't have write permissions.
@gissues:{"order":50,"status":"inprogress"}

**Comment by wysow** [comment]
@cuspide1988 Is this still relevant?

**Comment by rejinka** [comment]
we encountered this problem in the last few days and gave us a really hard time. I don't see, why we'd need write access here. The only reason would be to perhaps create the base-directory - but that's a side-effect, i wouldn't expect if i used file_exists().

**Comment by PedroTroller** [comment]
I close this issue. If anyone has a similar problem, please feel free to reopen it and add details of your problem.
