### ISSUE TITLE
LazyOpenCloud needed

### ISSUE THREAD

**Issue by lmammino** [KnpLabs/Gaufrette#163]
It would be good to have a variant of the OpenCloud adapter that issues authentication and loads the `ObjectStore` only when really trying to use the container (e.g. reading, writing or deleting a file) and not when we are just instancing the adapter.

OpenCloud library seems to automatically issue authentication when we call `$connection->ObjectStore(...)` that is needed to get the `ObjectStore` to instantiate the adapter.

So in some environment or with some frameworks (eg. Symfony with [KnpGaufretteBundle](https://github.com/KnpLabs/KnpGaufretteBundle)) it might happen that you always load an instance of your filesystem (eg. `FilesystemMap` with the KnpGaufretteBundle) ans so authentication is issued behind the scene for every single request to your web app even if you don't need to use the filesystem in that request... 
And this is definitely something bad!

**Comment by wysow** [comment]
@lmammino What the status of this? Should we close it?
