### ISSUE TITLE
Create specs and functional tests for OpenCloud adapter

### ISSUE THREAD

**Issue by lmammino** [KnpLabs/Gaufrette#166]
Hi, I'm developing a [lazy version of the OpenCloud adapter](https://github.com/KnpLabs/Gaufrette/issues/163) and I have already a [working prototype](https://github.com/lmammino/Gaufrette/commit/596e27d9ec2d50d95a19d5a3ebd0385adbbb2298), but I want to provide some test before creating a pull request.
My LazyOpenCloud adapter extends the original OpenCloud adapter so any problem with it will reflect in a problem on the new lazy variant.
Furthermore I'm going to use the OpenCloud adapter in production and I would love to have at least some functional test (but either having specs would be awesome) to be sure everything works fine. 

I would like to involve @james75, who originally wrote the OpenCloud adapter.

**Comment by wysow** [comment]
@lmammino What's the status of this? Should we close it?
