### ISSUE TITLE
Does OpenCloud adapter support (pseudo-hirarchical) folders?

### ISSUE THREAD

**Issue by lmammino** [KnpLabs/Gaufrette#167]
During an attempt to write funcional test for my [LazyOpenCloud adapter]() (variant of the OpenCloud adapter) I found some errors that may indicate there's no support for [pseudo-hirarchical folders](http://docs.openstack.org/api/openstack-object-storage/1.0/content/pseudo-hierarchical-folders-directories.html).

I haven't looked deeper in the code to see if [pseudo-hirarchical folders](http://docs.openstack.org/api/openstack-object-storage/1.0/content/pseudo-hierarchical-folders-directories.html) support really missing (i hope I'll have time to do  it soon). Anyway I adopted [tvision/RackspaceCloudFilesStreamWrapper](https://github.com/tvision/RackspaceCloudFilesStreamWrapper) and it seems to support [pseudo-hirarchical folders](http://docs.openstack.org/api/openstack-object-storage/1.0/content/pseudo-hierarchical-folders-directories.html), so, in case the feature is missing, we can look at this repo for inspirations.

\cc @james75

**Comment by wysow** [comment]
@lmammino Should we close this one?

**Comment by PedroTroller** [comment]
I close this stale issue. Please feel free to reopen it if necessary.
