### ISSUE TITLE
Adapter\Cache::exists

### ISSUE THREAD

**Issue by nmpolo** [KnpLabs/Gaufrette#179]
``` php
public function exists($key)
{
    return $this->source->exists($key);
}
```

Currently, the cache adapter just checks the source adapter to see whether a key exists. This means you lose a lot of the benefit of the cache if you have a slow connection to the source adapter. Would it make more sense to check the cache adapter first before falling back to checking the source if it doesn't exist in the cache?

**Comment by NiR-** [comment]
Cache adapter has been deprecated. Thank you for taking time to report this issue.
