### ISSUE TITLE
Amazon S3 - can't set the content type (images are downloaded, not send from S3 because of that)

### ISSUE THREAD

**Issue by burzum** [KnpLabs/Gaufrette#187]
With Gaufrette I can't set an image file on S3 to be displayed instead of being send to the browser. Take a look at this, this is the native solution to the problem I'm facing:
http://stackoverflow.com/questions/4751360/amazon-s3-image-downloading-instead-of-displaying-in-browser

But how can I do that with Graufrette? I've looked at the code of the adapter and can't see a way to do it. So I consider this as a missing feature or to me more like a blocker of using Gaufrette + S3 Adapter. :(

**Comment by malinda1986** [comment]
@burzum is it available in master branch ?

**Comment by burzum** [comment]
@malinda1986 I don't know, use git to check or ask the maintainer of Gaufrette.

**Comment by malinda1986** [comment]
@burzum thanks, will check
