### ISSUE TITLE
[Filesystem] File Object unaware of key change

### ISSUE THREAD

**Issue by pawski** [KnpLabs/Gaufrette#197]
Gaufrette fails on this test (added to Adapter/FunctionalTestCase).

``` php
    public function shouldUpdateFileObjectKeyWhenRenaming()
    {
        $fileObject = $this->filesystem->createFile('somefile');
        $fileObject->setContent('abc'); 

        $this->filesystem->rename('somefile', 'somenewfile');

        $fileObject->setContent('def'); 

        $this->assertFalse($this->filesystem->has('somefile'));
        $this->assertTrue($this->filesystem->has('somenewfile'));
        $this->assertEquals('def', $this->filesystem->read('somenewfile'));
    }
```

Tested on Adapter Local but it is a case of Filesystem.
After renaming operation FileObject key is not touched, so in result we have:
- two files "somefile", "somenewfile"
- content of "somefile" is "def"
- content of "somenewfile" is "abc"

**Comment by NiR-** [comment]
This has been fixed in #468. Thank you for taking to report this issue.
