### ISSUE TITLE
[RC] Amazon adapters should filter by directory when listing keys

### ISSUE THREAD

**Issue by alex88** [KnpLabs/Gaufrette#223]
The current implementation of keys() in the `AmazonS3` adapter lists all keys of the bucket, since it has the directory information I think it should instead return only the keys inside that folder.
I discovered this since when we write files like `foo1`, `foo2` etc. and I want to download all the files beginning with `foo` I would do `listKeys('foo')` on the filesystem but this fails since the returned keys has the directory in the string.

What you think?

**Comment by benoitMariaux** [comment]
:+1:
