### ISSUE TITLE
Files direct URL

### ISSUE THREAD

**Issue by ghost** [KnpLabs/Gaufrette#246]
So in my application the user uploads images and Im using Gaufrette to store it either locally in my staging environment or on S3 in production. i was thinking that there must be a way to access the direct URL for a file. whether it's local, S3, Dropbox ... etc. I know this won't be supported in all adapters but it'd be great if its exists in adapters that can support it.

**Comment by raistlin** [comment]
Why not merge this? https://github.com/K-Phoen/gaufrette-extras

**Comment by raistlin** [comment]
ping @stof

**Comment by stof** [comment]
@raistlin I'm not the maintainer of the library. I cannot merge anything

**Comment by NiR-** [comment]
I've implemented a way of resolving files URLs in [Gaufrette/extras](https://github.com/Gaufrette/extras). It's slightly different than [K-Phoen/gaufrette-extras](https://github.com/K-Phoen/gaufrette-extras): a decorator is still used but to decorate the filesystem rather than the adapter.
