### ISSUE TITLE
Could not write the key content

### ISSUE THREAD

**Issue by jspizziri** [KnpLabs/Gaufrette#279]
I get the following error when I try to write an uploaded file my Amazon S3 bucket

Could not write the "2014/04/24/53596551ee0ec.m4a" key content." at .../vendor/knplabs/gaufrette/src/Gaufrette/Filesystem.php line 113

**Comment by jonaguera** [comment]
A possible cause for this behavior is that server date&time is wrong. I have been messing up with this error for a while until I realised the problem was that my server datetime was wrong.

**Comment by cmthornton** [comment]
Thanks @jonaguera, you probably saved me a few hours. My clock was off by only a few minutes.

**Comment by numerogeek** [comment]
Another cause of this error could be that the directory you try to upload to does not exist on the bucket. 

You can specify it trough the config : 
'
        kyc_adapter:
            aws_s3:
                service_id: 'my_own_service.aws_s3.client'
                bucket_name: %aws_bucket_default%
                options:
                    directory: 'pictures'
'

**Comment by vquefelec** [comment]
In my case, I've resolved this by attaching the missing 'AmazonS3FullAccess' policy on my AmazonUser.

**Comment by broncha** [comment]
This is strange. I am getting that error when using localstorage!

**Comment by supun19** [comment]
Could not write the "11246017_952948928145692_3919764058477068346_n.jpg" key content.
500 Internal Server Error - RuntimeException 

i got this error 
i uset to vich uploader and Gaufrett use upload image to amozon s3 bucket

**Comment by jspizziri** [comment]
@supun19,

Revisited this issue in a different project a couple years later. I had a couple issues relating to bucket permissions in `S3` which were causing this an another error that I'll document here for the sake of anyone who might come across them.

### Could not write the "..." key content
This had to do directly with the permissions granted to the `IAM` user on the bucket. As @quef mentioned this could be solved by attaching the `AmazonS3FullAccess` to the `IAM` user however, this gives the user access for ALL actions on ALL buckets in your S3, which I personally wouldn't advise as users should have the lowest level of permissions required to do what they need. I solved this issue by creating a policy on my `IAM` user which gave them FULL access to a specific bucket like so:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1490579629000",
            "Effect": "Allow",
            "Action": [
                "s3:AbortMultipartUpload",
                "s3:DeleteBucketWebsite",
                "s3:DeleteObject",
                "s3:DeleteObjectVersion",
                "s3:GetAccelerateConfiguration",
                "s3:GetBucketAcl",
                "s3:GetBucketCORS",
                "s3:GetBucketLocation",
                "s3:GetBucketLogging",
                "s3:GetBucketNotification",
                "s3:GetBucketPolicy",
                "s3:GetBucketRequestPayment",
                "s3:GetBucketTagging",
                "s3:GetBucketVersioning",
                "s3:GetBucketWebsite",
                "s3:GetLifecycleConfiguration",
                "s3:GetObject",
                "s3:GetObjectAcl",
                "s3:GetObjectTagging",
                "s3:GetObjectTorrent",
                "s3:GetObjectVersion",
                "s3:GetObjectVersionAcl",
                "s3:GetObjectVersionTagging",
                "s3:GetObjectVersionTorrent",
                "s3:GetReplicationConfiguration",
                "s3:ListAllMyBuckets",
                "s3:ListBucket",
                "s3:ListBucketMultipartUploads",
                "s3:ListBucketVersions",
                "s3:ListMultipartUploadParts",
                "s3:PutAccelerateConfiguration",
                "s3:PutBucketAcl",
                "s3:PutBucketCORS",
                "s3:PutBucketLogging",
                "s3:PutBucketNotification",
                "s3:PutBucketPolicy",
                "s3:PutBucketRequestPayment",
                "s3:PutBucketTagging",
                "s3:PutBucketVersioning",
                "s3:PutBucketWebsite",
                "s3:PutLifecycleConfiguration",
                "s3:PutReplicationConfiguration",
                "s3:PutObject",
                "s3:PutObjectAcl",
                "s3:PutObjectTagging",
                "s3:PutObjectVersionAcl",
                "s3:PutObjectVersionTagging",
                "s3:ReplicateDelete",
                "s3:ReplicateObject",
                "s3:RestoreObject"
            ],
            "Resource": [
                "arn:aws:s3:::foobarbucket/*"
            ]
        }
    ]
}
```

Which leads to the second issue.

### The configured bucket \"foobarbucket\" does not exist.
This was a bit frustrating at first until I realized the problem. My user didn't have access to list the buckets in my account (which is necessary as Gaufrette does this to verify bucket existence with the php sdk). Whats more is that the `"s3:ListAllMyBuckets"` and `"s3:ListBucket"` permissions weren't doing anything as as stated above, my user only has access on `"arn:aws:s3:::foobarbucket/*"`. So I attached a second policy to the user which looks like the following:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1490580036000",
            "Effect": "Allow",
            "Action": [
                "s3:GetBucketAcl",
                "s3:GetBucketCORS",
                "s3:GetBucketLocation",
                "s3:GetBucketLogging",
                "s3:GetBucketNotification",
                "s3:GetBucketPolicy",
                "s3:GetBucketRequestPayment",
                "s3:GetBucketTagging",
                "s3:GetBucketVersioning",
                "s3:GetBucketWebsite",
                "s3:ListAllMyBuckets",
                "s3:ListBucket",
                "s3:ListBucketVersions"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        }
    ]
}
```

With these TWO policies your IAM user now has the proper access it needs. If there's a better way of doing this I'd love to know!

**Comment by NiR-** [comment]
@jspizziri I added a recommended IAM policy in #467. It is really close to what we're using for functional tests so it should work with no problem.

**Comment by efleon9** [comment]
> A possible cause for this behavior is that server date&time is wrong. I have been messing up with this error for a while until I realised the problem was that my server datetime was wrong.

Many thanks, you're my hero...
