### ISSUE TITLE
rackspace/php-opencloud

### ISSUE THREAD

**Issue by bitgandtter** [KnpLabs/Gaufrette#280]
any upgrade comming to version over 1.5.10? the documentation should have a hint about to use only versions under this 1.5.10

**Comment by yalg** [comment]
There is a deprecated version about racspace/php-opencloud.

> OpenStack users are recommended to use https://github.com/php-opencloud/openstack, which is the latest supported version of the SDK for OpenStack.

Which element forbid now usage of php-opencloud/openstack ?

**Comment by NiR-** [comment]
@yalg Mostly the lack of time and maintainer :( If you, or someone else reading this comment, are motivated to submit patches, feel free. We would be glad to merge it.
