### ISSUE TITLE
Incorrect file Created: time

### ISSUE THREAD

**Issue by JasonHanley** [KnpLabs/Gaufrette#317]
When you create a file with the local filesystem adapter, it sets the wrong creation time.

Expected: File Created: time set to current time
Result: File Created: time is set to the Created time of the directory

Note that Modified: and Accessed: times are set correctly.

OS: Windows 7
Version: dev-master

**Comment by beebop1032** [comment]
I tested and it seems to be correct

**Comment by NiR-** [comment]
Could you provide a reproducer please? And have you tested if you have the same bug when writing a file with `file_put_contents`? I don't see anything magic in Local adapter, that could cause this bug.

**Comment by beebop1032** [comment]
no @NiR- for me, its no a bug, its ok.

**Comment by NiR-** [comment]
Ha sorry :D Well, in that case I close it.
