### ISSUE TITLE
Github description contains 404 link

### ISSUE THREAD

**Issue by mattalexx** [KnpLabs/Gaufrette#325]
PHP5 library that provides a filesystem abstraction layer − will be a feast for your files!

http://knplabs.com/blog/csi/give-your-projects-a-gaufrette

**Comment by GromNaN** [comment]
The link should be: http://knplabs.com/en/blog/give-your-projects-a-gaufrette

**Comment by docteurklein** [comment]
fixed thanks

**Comment by stof** [comment]
@docteurklein the KnpLabs website should have kept 301 redirections for old blog URLs too

**Comment by docteurklein** [comment]
yep :/
