### ISSUE TITLE
[Filesystem] createFile should be done by a default FileFactory to allow customising File class

### ISSUE THREAD

**Issue by ruudk** [KnpLabs/Gaufrette#338]
I'd like to extend the default `Gaufrette\File` class with my own, extra, logic. But the only way to do that is by extending the `Gaufrette\Filesystem` class and overriding the `createFile` method which uses a private method `isFileInRegister`.

Another option would be to override the Adapters I'm using and implement the `FileFactory` interface. But that doesn't seem right either.

**Comment by NiR-** [comment]
Is this issue still relevant for you? Could you describe a bit more what you are/were trying to do?

IMHO `File` should be `final` and no extra logic should be put there. Did you try to use a decorator for your adapter(s)?
