### ISSUE TITLE
Example needed for dealing with Google Cloud Storage with Gaufrette

### ISSUE THREAD

**Issue by mappedinn** [KnpLabs/Gaufrette#355]
Good morning,
Is there any example or a example's link on how to configure Gaufrette for storing files on `google-cloud-storage`?

The only thing I found is that [link ][1] which is an adapter class for GoogleCloudStorage.

Thanks for you help...

[1]: https://github.com/KnpLabs/Gaufrette/blob/master/spec/Gaufrette/Adapter/GoogleCloudStorageSpec.php

**Comment by watermanio** [comment]
Hi,

I also struggled to get this working and needed to make a [pull request](https://github.com/KnpLabs/Gaufrette/pull/352) to get it working correctly with metadata, however once I got the hang of it, GCS works perfectly through the Gaufrette layer.

```
// Check for required config:
if (empty($config['gcsKey'])
    || empty($config['gcsBucket'])) {
        throw new Exception('Google Cloud Storage is missing required configuration keys');
}

$client = new Google_Client();
$client->setApplicationName('http://www.example.com');

$key = json_decode($config['gcsKey']);
$credentials = new Google_Auth_AssertionCredentials(
    $key->client_email,
    array(\Google_Service_Storage::DEVSTORAGE_FULL_CONTROL),
    $key->private_key
);

$client->setAssertionCredentials($credentials);
if ($client->getAuth()->isAccessTokenExpired()) {
    $client->getAuth()->refreshTokenWithAssertion($credentials);
}

$service = new Google_Service_Storage($client);
$adapter = new Gaufrette\Adapter\GoogleCloudStorage($service, $config['gcsBucket'], array(
    'acl' => 'public',
), true);
$filesystem = new Gaufrette\Filesystem($adapter);
```
At this point you are ready to use your new GCS connection....!

Hope that helps.

**Comment by watermanio** [comment]
Sorry I know this was super-late and you have probably got it nailed by now, but this project seems a bit dead and hopefully this will help anyone else with the same issues we had...!

**Comment by mappedinn** [comment]
@watermanio  thank you very much for being helpful.

I already solved the problem. You can find the [solution here][1]. Sorry for answering you late since I receive too much emails & I have not seen your notification.

The solution works with KnpGaufretteBundle.

One question: do you apply **Imagine** library filters on the images you upload to Google Cloud Storage?
Actually, I am trying to build a Google Cloud Storage Resolver similarly to the AWS S3 Resolver of the LiipImagineBundle. To have an overview on the objective, have a look on [this link][2].

Good luck

[1]: https://github.com/KnpLabs/KnpGaufretteBundle/issues/123
[2]: https://github.com/liip/LiipImagineBundle/issues/666
