### ISSUE TITLE
Phpseclib SFTP adapter improvements

### ISSUE THREAD

**Issue by akovalyov** [KnpLabs/Gaufrette#370]
- [ ] - docs needed for the adapter instantiation.
- [ ] - it should login to the server automatically. Currently one has to use it like [that](https://github.com/akovalyov/gaufrette-integration-tests/blob/1352994bfce289771939228a2704271429f350b1/features/bootstrap/AdapterProxyFactory.php#L22).

**Comment by NiR-** [comment]
@akovalyov I'm not sure about the second point: currently there is no adapter assuming the authentication responsibility. Developers needs to pass an authenticated connection to their external service to adapters (i.e. [Google Cloud Storage](https://github.com/NiR-/Gaufrette/blob/refacto/doc/doc/adapters/googleCloudStorage.md)).
