### ISSUE TITLE
awsS3 adaptor rename performs a copy

### ISSUE THREAD

**Issue by trq** [KnpLabs/Gaufrette#374]
The rename method within the awsS3 adaptor seems to copy, not rename.

https://github.com/KnpLabs/Gaufrette/blob/master/src%2FGaufrette%2FAdapter%2FAwsS3.php#L103

I'm wondering if this is somehow intentional or should it be deleting the $sourceKey after a successful copy? It looks like this logic exists within the AmazonS3 adaptor. https://github.com/KnpLabs/Gaufrette/blob/master/src%2FGaufrette%2FAdapter%2FAmazonS3.php#L135

**Comment by jzawadzki** [comment]
Hi @trq,

There is already pending pull request for that (#315) so hopefully should be fixed soon
