### ISSUE TITLE
CacheAdapter does not support MimeType

### ISSUE THREAD

**Issue by leroy0211** [KnpLabs/Gaufrette#375]
When using the CacheAdapter, how do we get the MimeType of a file?

**Comment by akovalyov** [comment]
@leroy0211  please, check [this](https://github.com/KnpLabs/Gaufrette/blob/master/src/Gaufrette/Filesystem.php#L309).

**Comment by akovalyov** [comment]
my bad, `CacheAdapter` doesn't implement `MimeTypeProvider` interface.

**Comment by leroy0211** [comment]
Indeed. We sure can extend this, but wouldn't it be nicer to have a CacheAdapter with the `MimeTypeProvider` interface? 
Or maybe 2 cache adapters. One without and 1 with the `MimeTypeProvider` interface.

Currently I'm trying to get the mimetype (with a cache adapter) like this:
```php
$sourceAdapter = new Gaufrette\Adapter\Ftp(...);
$targetAdapter = new Gaufrette\Adapter\Local(...);
$cacheAdapter = new Gaufrette\Adapter\Cache($sourceAdapter, $targetAdapter, 3600);
$filesystem = new Gaufrette\Filesystem($cacheAdapter);

$mimetype = $targetAdapter->mimeType([file]);
$content = $filesystem->read([file]);
```

But I would prefer:

```php
$mimetype = $filesystem->mimeType([file]);
```

**Comment by NiR-** [comment]
Thank you @leroy0211.

This adapter will be deprecated in the next release, see #464. I close this issue.
