### ISSUE TITLE
$username and $password arguments to PhpseclibSftp are never used

### ISSUE THREAD

**Issue by ianfp** [KnpLabs/Gaufrette#403]
The code in question:
```php
class PhpseclibSftp implements ...
{
    public function __construct(SFTP $sftp, $directory = null, $create = false, $username = null, $password = null)
    {
        $this->sftp = $sftp;
        $this->directory = $directory;
        $this->create = $create;
    }
```

You can see that the `$username` and `$password` arguments are never used. [The documentation](https://knplabs.github.io/Gaufrette/adapters/phpseclib-sftp.html) says:

```php
$sftp = new phpseclib\Net\SFTP($host = 'localhost', $port = 22);

$adapter = new Gaufrette\Adapter\PhpseclibSftp($sftp, $distantDirectory = null, $createDirectoryIfDoesntExist = false, $username = 'gaufrette', $password = 'gaufrette');
$filesystem = new Gaufrette\Filesystem($adapter);
```

but that doesn't work. One must instead do this:
```php
$sftp = new phpseclib\Net\SFTP($host = 'localhost', $port = 22);
$sftp->login($username, $password);

$adapter = new Gaufrette\Adapter\PhpseclibSftp($sftp, $distantDirectory = null, $createDirectoryIfDoesntExist = false);
$filesystem = new Gaufrette\Filesystem($adapter);
```

**Comment by akovalyov** [comment]
True. Initially login was inside the `phpseclib` adapter, but then we have internally reached an agreement that adapters shouldn't be aware of any login functionality. I will add a fix to that. Thank you for pointing it out.

**Comment by func0der** [comment]
Isn' this fixed?

**Comment by akovalyov** [comment]
@func0der the PR was not merged, so it was not fixed.
now it is in the master branch, will be in release in some time.
