### ISSUE TITLE
unable to list directory contents when using   ftp_rawlist with "al " option

### ISSUE THREAD

**Issue by videni** [KnpLabs/Gaufrette#410]
I found this problem after serveral hours digging, 

knplabs/gaufrette/src/Gaufrette/Adapter/Ftp.php

```
     $lines = ftp_rawlist($this->getConnection(), '-al ' . dirname($file));
```

if  remove "al " option, it works.  I have enabled the passive mode.

**Comment by NiR-** [comment]
Hello @videni, sorry for late answer.

Can you give us more detail about your issue? What's your FTP server, and which version is it?

**Comment by videni** [comment]
this can be closed.
