### ISSUE TITLE
Sia decentralized backup

### ISSUE THREAD

**Issue by kunkinkan** [KnpLabs/Gaufrette#422]
I'd ike to use a decentralized backup system such as Sia ( http://sia.tech ) - any chance it can be added?

These are the API docs:

https://github.com/NebulousLabs/Sia/tree/master/doc

**Comment by NiR-** [comment]
@kunkinkan Sorry for the late reply.

We're already struggling to maintain the current set of Adapters, so I don't think we will add a new one.

But feel free to create your own adapter and share it! :)
