### ISSUE TITLE
aws/aws-sdk-php v~2 dependency

### ISSUE THREAD

**Issue by eduardoconceicao** [KnpLabs/Gaufrette#426]
Is there any special reason why this bundle depends on version 2 of aws/aws-sdk-php.

I'm questioning because the version 2 of [aws/aws-sdk-php](https://packagist.org/packages/aws/aws-sdk-php) depends on guzzle/guzzle which is on abandoned project. On the other hand the new versions of [aws/aws-sdk-php](https://packagist.org/packages/aws/aws-sdk-php) (3.19.5 atm) depends not on [guzzle/guzzle](https://packagist.org/packages/guzzle/guzzle) but on [guzzlehttp/guzzle](https://packagist.org/packages/guzzlehttp/guzzle).

Can this dependency version be updated?

Thanks,
Eduardo

**Comment by redthor** [comment]
This is now quite important because quite a few packages have upgraded to [guzzlehttp/guzzle](https://packagist.org/packages/guzzlehttp/guzzle) and now we're getting errors because of classes appearing twice and inconsistencies between those classes. It'd be great to get this dependency updated.

**Comment by redthor** [comment]
Actually this appears a bit harder than just updating the composer.json file.

[rackspace/php-opencloud](https://github.com/rackspace/php-opencloud) also includes `guzzle/guzzle` and on it's homepage it says:

> this codebase which you are now looking at will enter end-of-life soon. For Rackspace Cloud users, a v2 is actively being worked on.

but actually, I cannot see a v2 branch for [rackspace/php-opencloud](https://github.com/rackspace/php-opencloud). There is this issue: 

https://github.com/rackspace/php-opencloud/issues/586

@jamiehannaford may know more about the status of updating php-opencloud to guzzlehttp

However, the **real** solution is to break Gaufrette into multiple packages:
http://php-and-symfony.matthiasnoback.nl/2014/04/theres-no-such-thing-as-an-optional-dependency/#the-solution

Then we could confine this message to the `knplabs/gaufrette-aws` and `knplabs/gaufrette-opencloud` packages and the impact would be minimal.

**Comment by eduardoconceicao** [comment]
👍
