### ISSUE TITLE
FTP Use Passive Connection

### ISSUE THREAD

**Issue by alberto-leon-crespo** [KnpLabs/Gaufrette#434]
I have a problem with FTP that has been configured in passive mode. More of servers return local ip address and php ftp client use this to work with FTP. You can connect but some funtionalities dont work.
I have a solution for the issue but is only valid for PHP >=5.6.

_In Gaufrette\Adapter\Ftp in connect() method after this code:

`
if (!$this->ssl) {
      ......
} else {
      ......
}
`

Adding the next code:

`
ftp_set_option($this->connection, FTP_USEPASVADDRESS, FALSE);
`

**Comment by KonstantinCodes** [comment]
LGTM 👍
