### ISSUE TITLE
[Feature] Support for multi-container Azure workflow

### ISSUE THREAD

**Issue by dkarlovi** [KnpLabs/Gaufrette#446]
Currently, the `AzureBlobStorage` adapter requires a single container name which will be filesystem root, it might try to create it.

If I'm using a single storage account to hold only one type of asset (say, only images), I'd like to use one container per image (which will hold the original and all the variants), much like for example Azure Media Services does. This also [seems to be a recommended way of doing things](http://stackoverflow.com/a/8159446/672885).

What could be done here is add an additional flag / mode which would take the storage key and use the part until the first slash, create a container (if it doesn't already exist) and use the rest of the path as key. Ie. 

    write('my/image/path.jpeg') // "my" = container, "image/path.jpeg" = key

Some sort of container default creation options should also be provided (for example, access mode), but I think it shouldn't be all that hard.

**Comment by NiR-** [comment]
Hello @dkarlovi,

[The `AzureBlobStorage` adapter already has a `$containerName` argument, and a `$create` one.](https://github.com/KnpLabs/Gaufrette/blob/master/src/Gaufrette/Adapter/AzureBlobStorage.php#L55).

Is this what you are looking for? Or is it something else?

**Comment by dkarlovi** [comment]
Hi @NiR-,

that's not really what I'm looking for. Having a container name predefined means you can only have one container at a time, where I'd like to have dynamic containers where each asset has its own container for its use (like, for example, Azure Media Services does).

Also, having `create: true` is somewhat clumsy as it's hard-coded to config: if you leave it to `true`, it throws an exception on each request except the first (at least it did in the last version I've tried). If you leave it to `false`, you can't just switch your Azure Blob Storage account, you need to do some maintenance upfront before you can start using it (create the container in question).

My proposed feature here would allow for containers behaving as "first level directories", where they would get auto-created if not already there, with adapter specific container options, for example having it be public by default.

**Comment by NiR-** [comment]
@dkarlovi ok, now I see what you're looking for: basically, for every write operation we would have to check if the container (first directory in the path) exists, right ?

In your opinion what would be the impact on billing and performance of such a strategy? If it's negligable for both the best would be to update the current adapter. In other case, I guess it would be better to create  a seperated adapter.

**Comment by dkarlovi** [comment]
@NiR- yes, exactly like that.

I don't think it would impact billing as (AFAIK) storage is billed per consumed asset size and transfer bandwidth, not counting API operations or metadata (containers are just metadata, they don't count as data). This switch should have no impact what so ever.

We could change the adapter's signature, but how would we keep BC then?

**Comment by dkarlovi** [comment]
@NiR- I'd like to tackle this, PR would be OK here? Do we keep BC here or do we just rework?

**Comment by NiR-** [comment]
@dkarlovi We would be glad to see it. We are still trying to not break existing code (we'll break things after the next minor release, preparing 1.0).

How do you plan to implement this feature? I'm a bit afraid further changes has to be done in two adapters. In the mean time it seems hard to decorate the current adapter.

**Comment by dkarlovi** [comment]
If we need to keep BC (for now) and also stay with one Azure adapter only, this might work:
1) default `$containerName` to null (as we're relaxing the API, not a BC break), https://github.com/KnpLabs/Gaufrette/blob/master/src/Gaufrette/Adapter/AzureBlobStorage.php#L55
2) if `$containerName === null`, `$create = false; $this->multiContainerMode = true`, 
3) if 2), on each method, assume key contains the container name, try to create it instead of `failIfContainerNotFound()` in `catch`  (this would minimize the number of additional API calls) and retry the operation.
4) we need to be able to specify adapter-level `CreateContainerOptions` which will get used when auto-creating the container

The last one would be on method-by-method basis:
1) `read()` should assume the container DOES exist, if MIGHT create it on failure
2) `write()` should assume the container DOES NOT exists, it SHOULD try to create it before writing to it

**Comment by NiR-** [comment]
@dkarlovi Sounds great! I'm eager to see your PR :)

**Comment by dkarlovi** [comment]
@NiR- great, I'll try to get it done this weekend. :+1:

**Comment by dkarlovi** [comment]
@NiR- against which branch should this PR be? I'm looking, master is current, 1.x is next? Current releases are from master, correct?

**Comment by NiR-** [comment]
@dkarlovi Yep current release are created from master. You should do it on master ;)

**Comment by dkarlovi** [comment]
This was fixed in #486, closing.
