### ISSUE TITLE
Missing tag

### ISSUE THREAD

**Issue by sload** [KnpLabs/Gaufrette#450]
Hello,

The last tag (0.2.1) doesn't include changes related to the Azure namespace (https://github.com/KnpLabs/Gaufrette/commit/b0a11603f3593695d06e264bf360f3cc7e12c653 on May 2016).

Is it possible to add a new tag (0.2.2) who includes these changes ?
It's currently not possible to use your bundle with Azure Blob ..

**Comment by mvhirsch** [comment]
I too think it's time to release a new version. 
Since the last commit to master c76d77238da8261a788fcf2f5e459f825795aa58 is stable, I think it would be sufficient enough, what do you think @NiR-?

**Comment by NiR-** [comment]
Hello @sload, @mvhirsch,

I've just released a new v0.3 version. 

Thank you for your interest in Gaufrette :)

**Comment by mvhirsch** [comment]
Thank you, too!

**Comment by sload** [comment]
Thank you @NiR- !
