### ISSUE TITLE
[RFC] Deprecate outdated adapters

### ISSUE THREAD

**Issue by NiR-** [KnpLabs/Gaufrette#464]
* [x] AclAwareAmazonS3
* [x] AmazonS3
* [x] Apc (should be replaced by a PSR-16 compliant adapter)
* [x] Cache
* [x] LazyOpenCloud
* [x] Sftp
* [x] Dropbox
* [x] MogileFS
* [x] GoogleCloudStorage (should be replaced by #427)

Steps:
* Add `trigger_error(E_USER_DEPRECATED, ...)` in the header of every adapter
* Add `@deprecated` tag to phpdoc

**Comment by stof** [comment]
:+1:

Can you list them ?

**Comment by alex-pex** [comment]
Please export the adapters to new repositories, so we can still rely on them on demand
(eg: KnpLabs/Gaufrette-AmazonS3-Adapter)

**Comment by NiR-** [comment]
@alex-pex These adapters are not maintained anymore, and didn't received any updates for months. They are available in the last release though, so I don't see any benefit from creating new repositories. If you're still relying on `AmazonS3` adapter, you should migrate to `AwsS3`.

**Comment by leroy0211** [comment]
I would also prefer to have some deprecated adapters in separate repo's. Some private storage providers I know (because I use them) use the version 1 AWS S3 api. Since they cannot update their api version, I am bound to gaufrette having to use the version 1 adapter. If you are going to deprecate them, I can never update to a newer gaufrette.

**Comment by NiR-** [comment]
@leroy0211 I don't see any benefit: we are not maintaining these deprecated adapters and we don't want to invest any time for them. In consequence, they are shipped in their most up-to-date state in v0.3.1.

Your comment makes me realize I gave little details about why we're doing this. Here it is: in the (really) near future we'll release a v0.4 with some bug fixes, and deprecation notices. It will be the last release for 0.x branch. After that we'll prepare a v1.0, removing deprecated adapters and fixing even more bugs. From that point we'll also start overhauling Gaufrette. Doing so with a bigger number of adapters means more work for us, and, as stated, we don't want and we simply can't (plus there's no rationale behind maintaining adapters for deprecated SDK/API).

In the end, what would bring such seperate repos? Nothing, because they would still depend on 0.x branch. And you'll still be stuck. However if you need/want to maintain one of these adapter and are ready to do what's needed when new core updates are released , go on: create your own repository! We could even brand it as the newest adapter to use and add some docs on our website.
