### ISSUE TITLE
Attempted to load class "Google_Http_Request" from namespace "Gaufrette\Adapter".

### ISSUE THREAD

**Issue by wieger** [KnpLabs/Gaufrette#470]
I get this error when I use the GoogleStorageAdapter:

> Attempted to load class "Google_Http_Request" from namespace "Gaufrette\Adapter".
Did you forget a "use" statement for another namespace?
500 Internal Server Error - ClassNotFoundException
Stack Trace
in vendor/knplabs/gaufrette/src/Gaufrette/Adapter/GoogleCloudStorage.php at line 98   -
```
        }
        if (class_exists('Google_Http_Request')) {
            $request = new Google_Http_Request($object->getMediaLink());
            $this->service->getClient()->getAuth()->sign($request);
            $response = $this->service->getClient()->getIo()->executeRequest($request);
            if ($response[2] == 200) {

```
I had this working, but at some point after updating some dependencies through composer this error appeared.
The error disappears If I change line 98 to:
```
$request = new \Google_Http_Request($object->getMediaLink());

```

or add a use statement in Gaufrette\Adapter\GoogleStorageAdapter.php
`use Google_Http_Request;`

Is this a bug in the GoogleStorageAdapter or am I missing something?

Regards
Wieger Uffink

**Comment by AntoineLelaisant** [comment]
Hi, thanks for the feedback !

I think #471 will fix it :)

**Comment by wieger** [comment]
Thanks!
