### ISSUE TITLE
Local adapter read doesn't throw an error when accidentally reading a directory

### ISSUE THREAD

**Issue by burzum** [KnpLabs/Gaufrette#473]
We've had the case that file was stored properly but only a path like `/some/path/' was stored in the DB. The file was actually saved to the local file system.

So what happens now when passing that path to read() is that you get an empty result back but no exception like when the file is not found.

I've checked the code https://github.com/KnpLabs/Gaufrette/blob/master/src/Gaufrette/Adapter/Local.php#L80 and it is using file_exists() which doesn't make a difference between file and folder, so it was reporting true back.

The method is missing an is_dir() check.

**Comment by AntoineLelaisant** [comment]
Hi thanks for the feedback ! I just open a PR #479 to fix that.

**Comment by burzum** [comment]
Thank you!
