### ISSUE TITLE
Implement pre-signed operation on AWS S3 adapter

### ISSUE THREAD

**Issue by renatogcarvalho** [KnpLabs/Gaufrette#485]
Hello folks,

First of all, thank you for this amazing package! I've been using for quite some time and it makes it so much easier to abstract the filesystem across multiple environments.

However, one feature that I believe we're currently missing is the ability to build pre-signed URLs on the AWS S3 adapter. Sometimes even though your bucket is not public you may still want to grant temporary access to some of your files in some fashion.

With that said, is there a chance we can implement the pre-signed operation? It would be great if we could use the adapter directly instead of building the request manually ourselves.

Let me know if this feature is something that you consider viable and I could make a pull request for this.

Best Regards.

Reference:
https://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-presigned-url.html#creating-a-presigned-url

**Comment by NiR-** [comment]
Hello @renatogcarvalho, 

Thank you for your interest in Gaufrette. I think this feature is sometimes useful *when* using AWS, as I had to do this myself months ago. In the mean time it's totally specific to this storage, therefore adding such method would clutter the API and undermine our goal: abstracts underlying storages.

For now the best is to inherit `AwsS3` adapter and add this method:
```
    public function getPresignedUrl($key)
    {
        $command = $this->service->getCommand('GetObject', [
            'Bucket' => $this->bucket,
            'Key'    => $this->computePath($key),
        ]);

        return (string) $this->service->createPresignedRequest($command, new \DateTime('+12 hour'))->getUri();
    }
```
