### ISSUE TITLE
AwsS3 adapter not compatible with aws SDK v3

### ISSUE THREAD

**Issue by karim-elshendy** [KnpLabs/Gaufrette#495]
I'm using aws-sdk v3 and when I call getUrl method with "expires" option it does not affect the generated url because the aws-sdk v3 S3Client "getObjectUrl" method do not take options anymore. they added a new method for that purpose called "createPresignedRequest"

**Comment by karim-elshendy** [comment]
I have changed the getUrl method in aws-s3 adapter to consider this case as following:
is that a best practice or we should create a new adapter for aws-s3-sdk v3?

public function getUrl($key, array $options = [])
    {
        $expires = isset($options['expires']) ? $options['expires'] : null;

        # aws SDK v2 condition
        if ($this->service instanceof \Aws\Common\Client\AbstractClient) {
            return $this->service->getObjectUrl(
                $this->bucket,
                $this->computePath($key),
                $expires,
                $options
            );
        }
        # aws SDK v3 condition
        elseif ($this->service instanceof \Aws\AwsClient) {
            if ($expires) {
                $cmd = $this->service->getCommand('GetObject', [
                    'Bucket' => $this->bucket,
                    'Key'    => $this->computePath($key)
                ]);

                $request = $this->service->createPresignedRequest($cmd, $expires);
                return $request->getUri()->__toString();
            } else {
                return $this->service->getObjectUrl(
                    $this->bucket,
                    $this->computePath($key)
                );
            }
        }

        return null;
    }

**Comment by NiR-** [comment]
Hello, thank you for the report. Actually we're deprecating `AwsS3::getUrl` in favor of the newly created pakage `gaufrette/extras`. I created [a PR](https://github.com/Gaufrette/extras/pull/3) earlier today to add support for v2.
