### ISSUE TITLE
Docker image fails to build.

### ISSUE THREAD

**Issue by MonsieurLanza** [KnpLabs/Gaufrette#509]
While trying to build the docker image to run tests, I get the following error, preventing the whole image to build : 

ERROR: file /tmp/pear/temp/tmppadGFb/ssh2-1.1.1/tests/ssh2_auth.phpt does not exist
ERROR: Service 'php71' failed to build: The command '/bin/sh -c apt-get update &&     apt-get install -y --no-install-recommends         git         libssh2-1-dev         libssl-dev         unzip         libzip-dev     && rm -rf /var/lib/apt/lists/* &&     pecl install mongodb ssh2-alpha zip &&     echo 'extension=/usr/local/lib/php/extensions/no-debug-non-zts-20160303/mongodb.so' >> /usr/local/etc/php/conf.d/mongodb.ini &&     echo 'extension=/usr/local/lib/php/extensions/no-debug-non-zts-20160303/ssh2.so' >> /usr/local/etc/php/conf.d/ssh2.ini &&     echo 'extension=/usr/local/lib/php/extensions/no-debug-non-zts-20160303/zip.so' >> /usr/local/etc/php/conf.d/zip.ini' returned a non-zero code: 1

Seems related to :
https://bugs.php.net/bug.php?id=74787

**Comment by NiR-** [comment]
:+1: Also the `tests` script is broken. I fix it.
