### ISSUE TITLE
Local adapter cant delete empty directory

### ISSUE THREAD

**Issue by JanisGruzis** [KnpLabs/Gaufrette#524]
While using Local adapter when i try to delete empty directory i get issue when check happens if key exists. The check for key only checks if it is file - https://github.com/KnpLabs/Gaufrette/blob/master/src/Gaufrette/Adapter/Local.php#L94

I think this is not proper since directories should also be considered a keys and should be deleted if they are empty. Is this a bug or intended like that?

**Comment by Aerendir** [comment]
Same problem here...

For the moment I've solved with a very hacky way:

```php
        $folderContent = $filesystem->listKeys($domainFolder);
        ....
        $adapter = null;
        if (method_exists($filesystem, 'getAdapter')) {
            $adapter = $filesystem->getAdapter();
        }

        if ($adapter instanceof Local) {
            $adapter->delete($folderContent['dirs'][0]);
        }
```

But this really makes my code hard dependent on the `Local` adapter and this practically removes the usefulness of Gaufrette.

**Comment by nicolasmure** [comment]
With the merge of #610 , the local adapter can now be used to delete directories.
As explained, we aim to move the filesystem abstraction to object storage abstraction, where the directory concept is not available.
Considering this, you have to explicitly use the Local adapter in order to delete a directory :
```php
$filesystem->getAdapter()->delete($dirKey);
```

**Comment by Aerendir** [comment]
@nicolasmure , ok, the concept of directory is not available. But anyway there is something like "object that contains other objects": so, also if we don't call it "directory", anyway maybe a method that deletes the object and all its children is anyway useful, isn't it?
