### ISSUE TITLE
This function may return Boolean FALSE, but may also return a non-Boolean value which evaluates to FALSE. 

### ISSUE THREAD

**Issue by gregsparrow** [KnpLabs/Gaufrette#560]
https://github.com/KnpLabs/Gaufrette/blob/0cf2aeb64958badce437d1906a814bc85f1a5838/src/Gaufrette/Adapter/Local.php#L64

This function returns the number of bytes that were written to the file, or FALSE on failure.
This function may return Boolean FALSE, but may also return a non-Boolean value which evaluates to FALSE. Use the === operator for testing the return value of this function.

```
        $writedBytes = @file_put_contents($path, $content);
        if ($writedBytes === FALSE) {
            throw StorageFailure::unexpectedFailure('write', ['key' => $key]);
        }

        return $writedBytes;

```

**Comment by nicolasmure** [comment]
Thank you for pointing this out @gregsparrow :+1:
