### ISSUE TITLE
duplicated files

### ISSUE THREAD

**Issue by grekpg** [KnpLabs/Gaufrette#583]
I read files 

$filesystem = $this->container->get('gaufrette.product_uploads_ftp_fs_filesystem');

 $filesystem->listKeys()

result is 

     0 => "vp_Service_v3_001.png"
        1 => "vp_Service_v3_001_thumb.jpg"
        2 => "vp_Service_v3_036.png"
        3 => "vp_Service_v3_036_thumb.jpg"
        4 => "vp_Service_v3_044.png"
        5 => "vp_Service_v3_044_thumb.jpg"
        6 => "vp_HDRi_v3_01.hdr"
        7 => "vp_HDRi_v3_01_thumb.png"
        8 => "vp_HDRi_v3_03.hdr"
        9 => "vp_HDRi_v3_03_thumb.png"
        10 => "test/vp_HDRi_v3_01.hdr"
        11 => "test/vp_HDRi_v3_01_thumb.png"
        12 => "test/vp_HDRi_v3_03.hdr"
        13 => "test/vp_HDRi_v3_03_thumb.png"

Files 6,7,8,9, 

not exist in / just in test why i get it twice ?

**Comment by nicolasmure** [comment]
Hello :)

I don't think the adapter is creating such files, what's the output of `$ ls -lah` command on this directory ?

**Comment by KevinArtus** [comment]
I close this stale issue. Please feel free to reopen it if necessary.
