### ISSUE TITLE
OpenCloud\OpenStack adapter not working with identity api V3?

### ISSUE THREAD

**Issue by benIT** [KnpLabs/Gaufrette#584]
Hi,
I am trying to use the [`OpenCloud\OpenStack` adapter](https://github.com/KnpLabs/Gaufrette/blob/master/doc/adapters/open-cloud.md#opencloud-example).
This is not working and a 404 error is returned, see stack trace below:

```
[status code] 404
[reason phrase] Not Found
[url] https://identity.api.pi.company.com/v3/tokens in /vagrant/shared/swift-sandbox/vendor/guzzle/guzzle/src/Guzzle/Http/Exception/BadResponseException.php:43
Stack trace:
#0 /vagrant/shared/swift-sandbox/vendor/guzzle/guzzle/src/Guzzle/Http/Message/Request.php(145): Guzzle\Http\Exception\BadResponseException::factory(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Message\Response))
#1 /vagrant/shared/swift-sandbox/vendor/symfony/event-dispatcher/EventDispatcher.php(184): Guzzle\Http\Message\Request::onRequestError(Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 /vagrant/shared/swift-sandbox/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'request.error', Object(Guzzle\Common\Event))
#3 /vagrant/shared/swift-sandbox/vendo in /vagrant/shared/swift-sandbox/vendor/guzzle/guzzle/src/Guzzle/Http/Exception/BadResponseException.php on line 43
```
Code snippet:

```
<?php
$env = [];
$env['username'] = getenv('OS_USERNAME');
$env['password'] = getenv('OS_PASSWORD');
$env['project_name'] = getenv('OS_PROJECT_NAME');//v2: OS_TENANT_NAME VS v3: OS_PROJECT_NAME
$env['project_id'] = getenv('OS_PROJECT_ID');
$env['auth_url'] = getenv('OS_AUTH_URL');
$env['region_name'] = getenv('OS_REGION_NAME');
$env['domain_name'] = getenv('OS_USER_DOMAIN_NAME');

echo sprintf('checking env var %s', PHP_EOL);
foreach ($env as $key => $value) {
    if (!$value) {
        die(sprintf("please set '%s' env var.", $key));
    } else {
        echo sprintf("%s : %s %s", $key, $value, PHP_EOL);
    }
}
echo sprintf('checking env var ends %s', PHP_EOL);

$connection = new OpenCloud\OpenStack(
    $env['auth_url'],
    array(
        'username' => $env['username'],
        'password' => $env['password'],
        'tenantName' => $env['project_name'],
    )
);

$objectStore = $connection->objectStoreService('cloudFiles', 'LON', 'publicURL');

$adapter = new OpenCloudAdapter(
    $objectStore,
);
```

**Does any one know if this adapter is still working with openstack identity api V3? Any help would be appreciated.**

I guess that the `domain` information must be passed in V3 but I am not very confortable with openstack yet.

Credentials are ok, I use them with the python CLI that is working fine.

**Comment by nicolasmure** [comment]
Hello :)

Identity v3 is [planned for the v1 release](https://github.com/KnpLabs/Gaufrette/pull/533). If you wish to use it right now, consider to look at [our doc](https://github.com/KnpLabs/Gaufrette/blob/34aa8484f599495df4f66c89c9c6dbc7e5cdd76b/doc/adapters/open-stack.md#usage-with-identity-api-v3) for example and also to use the [`php-opencloud/openstack`](https://github.com/php-opencloud/openstack) v3 library.

**Comment by benIT** [comment]
Hi @nicolasmure,
That's a good news!
I tested the `php/open-cloud` client but unfortunately it was not sucessfully, documentation seems to be out of date [as I mentioned here](https://github.com/php-opencloud/openstack/issues/260)
I am looking forward to testing your openstack adapter.
Thank you for your work.
Greetings,
Ben

**Comment by benIT** [comment]
Hi,
PR #533 has been merged a few days ago  in the 1.x branch. The new [Openstack adapter](https://github.com/KnpLabs/Gaufrette/blob/1.x/src/Gaufrette/Adapter/OpenStack.php) based on [php-opencloud/openstack](https://github.com/php-opencloud/openstack) is now available!

Thanks so much for your work @nicolasmure!

**Comment by SebCargo** [comment]
@benIT is the branch 1.x safe to use ?

**Comment by benIT** [comment]
hi @SebCargo, I am not working on these day, I cannot answer you safely.
Cheers

**Comment by chadyred** [comment]
Mine works. I do a PR on Gaufrette itself....

https://github.com/chadyred/Gaufrette/tree/1.x

**Comment by Nek-** [comment]
Gaufrette is end on its road to end of life. The support of opencloud has been removed because nobody maintained it for years and libraries are not compatible with new versions of PHP. see https://github.com/KnpLabs/Gaufrette/pull/669
