### ISSUE TITLE
[Azure] support ChecksumCalculator for AzureBlobStorage

### ISSUE THREAD

**Issue by dkarlovi** [KnpLabs/Gaufrette#590]
[Azure Blob Storage stores an MD5 checksum with each blob](https://blogs.msdn.microsoft.com/windowsazurestorage/2011/02/17/windows-azure-blob-md5-overview/). It would make sense to expose that functionality in the adapter by implementing `ChecksumCalculator`.

**Comment by dkarlovi** [comment]
A [quick example](https://github.com/Azure/azure-storage-php/blob/c6fd3d949e94b634305255d9a29fe70a147fb356/samples/BlobSamples.php#L283-L291) shows how the checksum is available as part of "blob properties", implementation should be trivial.

**Comment by nicolasmure** [comment]
Closed by https://github.com/KnpLabs/Gaufrette/pull/594 .
