### ISSUE TITLE
phpseclib adapter connections not closed properly

### ISSUE THREAD

**Issue by l0wskilled** [KnpLabs/Gaufrette#605]
Hi there.

Im using gaufrette with the phpseclib sftp adapter.
Serveral files are being transfered via sftp to an external server.
It runs on php 5.6.40 on an ubuntu machine.

I have lots of non closed connections at all times.
I also experience failed connections.
I first thought this https://blog.cloudflare.com/this-is-strictly-a-violation-of-the-tcp-specification/ could be the same problem but i don't have that many used ports.

```CLOSE-WAIT 1      0           xxx.xxx.xxx.xxx:33487      xxx.xxx.xxx.xxx:ssh      users:(("php",27794,3))
CLOSE-WAIT 1      0           xxx.xxx.xxx.xxx:33578      xxx.xxx.xxx.xxx:ssh      users:(("php",27802,3))
CLOSE-WAIT 1      0           xxx.xxx.xxx.xxx:50573      xxx.xxx.xxx.xxx:ssh      users:(("php",26172,3))
CLOSE-WAIT 1      0           xxx.xxx.xxx.xxx:51369      xxx.xxx.xxx.xxx:ssh      users:(("php",26265,3))
CLOSE-WAIT 1      0           xxx.xxx.xxx.xxx:51314      xxx.xxx.xxx.xxx:ssh      users:(("php",26250,3))
CLOSE-WAIT 1      0           xxx.xxx.xxx.xxx:51509      xxx.xxx.xxx.xxx:ssh      users:(("php",26286,3))
CLOSE-WAIT 1      0           xxx.xxx.xxx.xxx:60972      xxx.xxx.xxx.xxx:ssh      users:(("php",29710,3))
CLOSE-WAIT 1      0           xxx.xxx.xxx.xxx:51189      xxx.xxx.xxx.xxx:ssh      users:(("php",26241,3))
CLOSE-WAIT 1      0           xxx.xxx.xxx.xxx:51082      xxx.xxx.xxx.xxx:ssh      users:(("php",26222,3))
CLOSE-WAIT 1      0           xxx.xxx.xxx.xxx:33436      xxx.xxx.xxx.xxx:ssh      users:(("php",27790,3))
CLOSE-WAIT 1      0           xxx.xxx.xxx.xxx:51116      xxx.xxx.xxx.xxx:ssh      users:(("php",26229,3))
CLOSE-WAIT 1      0           xxx.xxx.xxx.xxx:51435      xxx.xxx.xxx.xxx:ssh      users:(("php",26274,3))
CLOSE-WAIT 1      0           xxx.xxx.xxx.xxx:33437      xxx.xxx.xxx.xxx:ssh      users:(("php",27791,3))
CLOSE-WAIT 1      0           xxx.xxx.xxx.xxx:33515      xxx.xxx.xxx.xxx:ssh      users:(("php",27799,3))
CLOSE-WAIT 1      0           xxx.xxx.xxx.xxx:50998      xxx.xxx.xxx.xxx:ssh      users:(("php",26213,3))
CLOSE-WAIT 1      0           xxx.xxx.xxx.xxx:50883      xxx.xxx.xxx.xxx:ssh      users:(("php",26204,3))
```

Has anyone ever experienced that?
I tried unsetting the gaufrette filesystem in a finally block (because phpseclib does disconnect in deconstructor). This hasn't helped.
I tried extending the filesystem to make the disconnect method publicly available - didn't help either.

I'm monitoring the connections with `ss -tp | grep -P "^[^T].*xxx.xxx.xxx.xxx:ssh"`.
There are successful (established -> then propery closed) connections while the CLOSE WAITs are going on. 
On the CLOSE WAIT i also see the process change - so I guess there is still stuff going on in this processes.

**Comment by mahho** [comment]
Any solution? I have same problem now

**Comment by l0wskilled** [comment]
I just started creating and destroying a connection for each file.

**Comment by mahho** [comment]
Hi, thx for reply and a future solution. I've moved file uploading to nfs
