### ISSUE TITLE
How to update metadata of file in GridFS

### ISSUE THREAD

**Issue by averichev** [KnpLabs/Gaufrette#624]
Please, tell me, how i can update file metadata after write.

my code

```php
$gridFSAdapter->write($fileName, $file->getContent());
$gridFSAdapter->setMetadata($fileName, [
    'mimeType' => $uploadedFile->getMimeType(),
    'clientOriginalExtension' => $uploadedFile->getClientOriginalExtension(),
    'clientOriginalName' => $uploadedFile->getClientOriginalName(),
    'uploadUserId' => $this->getUser()->getId(),
]);
```

@NiR- ?

**Comment by nm2107** [comment]
Hello,

From the gridFS code, the `setMetadata` function only stores it in memory : https://github.com/KnpLabs/Gaufrette/blob/master/src/Gaufrette/Adapter/GridFS.php#L153-L159

you have to call `write` to persist the metadata on the storage : https://github.com/KnpLabs/Gaufrette/blob/master/src/Gaufrette/Adapter/GridFS.php#L51-L65

so, with your snippet :

```php
$gridFSAdapter->getMetadata($key , $value);
$gridFSAdapter->write($key, $content);
```
