### ISSUE TITLE
Add a .gitattributes file

### ISSUE THREAD

**Issue by williamdes** [KnpLabs/Gaufrette#649]
![image](https://user-images.githubusercontent.com/7784660/113601991-5bf93a00-9642-11eb-923d-0ec135be0818.png)

Remove everything that is related to tools, github, docker, CIs
Keep the tests for people packaging this lib and the phpunit config file. Also keep source files, but nothing more.

**Comment by williamdes** [comment]
Bonjour @Nek- 
Maybe you will be interested by this one, you seem to have done some cleanups

**Comment by Nek-** [comment]
PR welcome!
