### ISSUE TITLE
pulse & plans for the 1.x branch

### ISSUE THREAD

**Issue by desjob** [KnpLabs/Gaufrette#654]
Hi,

I was checking out the 1.x branch because i'm interested in the updated OpenStack adapter. However the commits on this branch are already a few years old, and I noticed it has been a while since there were any pull requests merged in general. Are there any plans for an official release of the 1.x branch? And can I count on this project still being maintained in the near future? (i.e. PHP8 compatability, with PHP7 nearing end of support)

**Comment by Nek-** [comment]
Hello @desjob . 1.x branch seems to be abandoned. I'm interested in merging some work on master branch if you want to update the OpenStack adapter.

**Comment by desjob** [comment]
Thanks for your reply. I have a fork of the OpenStack apdater from the 1.x branch in a private repository, that we have been using in production for a while now. I can submit it as a pull request. One option is to have it as a replacement for the existing OpenCloud adapter, since that is based on `rackspace/php-opencloud` which is no longer maintained. That would however mean that there will need to be a new major version release for https://github.com/Gaufrette/opencloud-adapter/ . Do you also have write access to that repository? 

An alternative is to add it as a new adapter (i.e.  openstack-adapter) and deprecate the other one. But I guess that would also need a second repository for enabling the adapter (e.g. https://github.com/Gaufrette/openstack-adapter/ ).

Let me know what you prefer!

**Comment by desjob** [comment]
Also happy to see work PHP 8 support! 🥳

**Comment by Nek-** [comment]
The next release of Gaufrette is a major one. You can go for a replacement! If you take that work, it's really a great help for me so thank you for any effort on it!

For now in order to test the adapter the related library is installed on build: https://github.com/KnpLabs/Gaufrette/blob/f3537658c37edd7f96c454b829ac61fa4fe60b1a/Makefile#L49

But it's not compatible with PHP 8+ anymore, removing this to install the new one would be definitely a great improvement.

**Comment by Nek-** [comment]
Since [nobody seems to care](https://twitter.com/Nekdev/status/1575876757525524480) about this problem, [I removed the support for OpenCloud](https://github.com/KnpLabs/Gaufrette/pull/669) for the next version. (was not working anyway)
