### ISSUE TITLE
:wrench: Cleaning build stuff

### ISSUE THREAD

**Issue by Nek-** [KnpLabs/Gaufrette#684]
This project has a lot, A LOT of build tools. This is because it's not that easy to run the test suite.

It would be super cool to add a "how to" run the test suite. As well as
- removing the Travis configuration
- testing on low dependencies
- upgrading the docker-compose configuration to allow to test things like the FTP or sftp adapter easily...

The folder `bin` is weird but necessary and should be cleaned. The `Makefile` looks incomplete.

There's a lot of work, I'm opening an issue that has the goal to at least list all of this since @williamdes was open to help :) .

**Comment by williamdes** [comment]
Still up to review PRs :)

**Comment by Nek-** [comment]
@williamdes it would be great if somebody could maintain Gaufrette. I do not want to maintain Gaufrette (and I also do not have the right anymore). If you want to maintain this project you can try to reach KnpLabs to get the merge right.

**Comment by williamdes** [comment]
> @williamdes it would be great if somebody could maintain Gaufrette. I do not want to maintain Gaufrette anymore (and I also do not have the right anymore). If you want to maintain this project you can try to reach KnpLabs to get the merge right.

Thanks, I do not use this project currently
